### ISSUE TITLE
[Feature Request] Invalid Login Shell

### ISSUE THREAD

**Issue by simon-Leary42** [UnityHPC/unity-web-portal#15]
One hard to debug issue with comes up when users enter the wrong thing in their login shell. One way to prevent this would be to take the input from the textbox and use PHP to ask the web node whether such a shell exists, but realistically people only use bash and zsh, so a simpler solution would be to make it a dropdown: bash, zsh, custom. And if people choose custom then they probably know what they're doing. We can't remove the login shell feature from the user portal entirely because it has to be done through LDAP.

**Comment by hakasapl** [comment]
Login shells should be listed in branding/config.ini under `[loginshell]` section, then ready with `$BRANDING["loginshell"]["shell"]` Example:

```
[loginshell]
shell[] = "/bin/bash"
shell[] = "/bin/zsh"
...
```

The file that parses config.ini is in https://github.com/UnityHPC/unity-web-portal/blob/main/resources/lib/UnityBranding.php
