### ISSUE TITLE
Add user to Google group upon account creation or email update

### ISSUE THREAD

**Issue by georgiastuart** [UnityHPC/unity-web-portal#83]
We're primarily using the Google group for communication and right now I try to update manually before sending out notices. I think Google groups can be interacted with via API, so would it be possible to add a hook to add users upon account creation or email update?

**Comment by hakasapl** [comment]
We are planning on implementing this in a more general way. The web portal will expose an API for this info for any external scripts, but it will also include a folder in the deployment folder where the deployment can put custom scripts that will do things like this. Closing this for now in favor of [that method](https://github.com/UnityHPC/unity-web-portal/issues/93)
