### ISSUE TITLE
import empty github username adds invalid keys to account

### ISSUE THREAD

**Issue by simonLeary42** [UnityHPC/unity-web-portal#90]
![image](https://github.com/UnityHPC/unity-web-portal/assets/71396965/77b9d82b-9119-46c1-b20d-58fc23b79497)

`Account Settings` > `+` > `Import from GitHub` > `Import Key(s)`

**Comment by simonleary-umass-edu** [comment]
`N` and `h` came from github, if it isn't obvious

**Comment by hakasapl** [comment]
Fixed with https://github.com/UnityHPC/unity-web-portal/pull/102
